{
  "Software_Repo_MappingId": null,
  "Software_RepoId": "f6b863cd-8f1c-4583-8bc5-ee59e86e5cf1",
  "Software_Name": "Python 3.12.5 (64-bit)",
  "CVEID": "CVE-2021-4189",
  "Summary": "A flaw was found in Python, specifically in the FTP (File Transfer Protocol) client library in PASV (passive) mode. The issue is how the FTP client trusts the host from the PASV response by default. This flaw allows an attacker to set up a malicious FTP server that can trick FTP clients into connecting back to a given IP address and port. This vulnerability could lead to FTP client scanning ports, which otherwise would not have been possible.",
  "LastUpdate": 0,
  "CVEE": {
    "CVEEId": "CVE-2021-4189",
    "CVSS_V2_baseScore": null,
    "CVSS_V2_Data": null,
    "CVSS_V3_baseScore": 5.3,
    "CVSS_V3_Data": "{\"version\":\"3.1\",\"baseScore\":5.3,\"accessVector\":null,\"vectorString\":\"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N\",\"authentication\":null,\"integrityImpact\":\"NONE\",\"accessComplexity\":null,\"availabilityImpact\":\"NONE\",\"confidentialityImpact\":\"LOW\",\"scope\":\"UNCHANGED\",\"attackVector\":\"NETWORK\",\"baseSeverity\":\"MEDIUM\",\"userInteraction\":\"NONE\",\"attackComplexity\":\"LOW\",\"privilegesRequired\":\"NONE\"}",
    "PublishedDate": "2022-08-24T16:15:09.827",
    "ModifyDate": "2024-11-21T06:37:06.437",
    "VulnStatus": "Modified",
    "JsonData": "{\"id\": \"CVE-2021-4189\", \"summary\": \"A flaw was found in Python, specifically in the FTP (File Transfer Protocol) client library in PASV (passive) mode. The issue is how the FTP client trusts the host from the PASV response by default. This flaw allows an attacker to set up a malicious FTP server that can trick FTP clients into connecting back to a given IP address and port. This vulnerability could lead to FTP client scanning ports, which otherwise would not have been possible.\", \"created_at\": \"2022-08-24T16:15:09Z\", \"updated_at\": \"2024-11-21T06:37:06Z\", \"cvss\": {\"v2\": null, \"v3\": 5.3}, \"vendors\": {\"python\": [\"python\"], \"debian\": [\"debian_linux\"], \"redhat\": [\"enterprise_linux\", \"software_collections\"], \"netapp\": [\"ontap_select_deploy_administration_utility\"]}, \"cwes\": [\"CWE-252\"], \"raw_nvd_data\": {\"id\": \"CVE-2021-4189\", \"metrics\": {\"cvssMetricV31\": [{\"type\": \"Primary\", \"source\": \"nvd@nist.gov\", \"cvssData\": {\"scope\": \"UNCHANGED\", \"version\": \"3.1\", \"baseScore\": 5.3, \"attackVector\": \"NETWORK\", \"baseSeverity\": \"MEDIUM\", \"vectorString\": \"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N\", \"integrityImpact\": \"NONE\", \"userInteraction\": \"NONE\", \"attackComplexity\": \"LOW\", \"availabilityImpact\": \"NONE\", \"privilegesRequired\": \"NONE\", \"confidentialityImpact\": \"LOW\"}, \"impactScore\": 1.4, \"exploitabilityScore\": 3.9}]}, \"published\": \"2022-08-24T16:15:09.827\", \"references\": [{\"url\": \"https://access.redhat.com/security/cve/CVE-2021-4189\", \"tags\": [\"Third Party Advisory\"], \"source\": \"secalert@redhat.com\"}, {\"url\": \"https://bugs.python.org/issue43285\", \"tags\": [\"Patch\", \"Vendor Advisory\"], \"source\": \"secalert@redhat.com\"}, {\"url\": \"https://bugzilla.redhat.com/show_bug.cgi?id=2036020\", \"tags\": [\"Issue Tracking\", \"Patch\", \"Third Party Advisory\"], \"source\": \"secalert@redhat.com\"}, {\"url\": \"https://github.com/python/cpython/commit/0ab152c6b5d95caa2dc1a30fa96e10258b5f188e\", \"tags\": [\"Patch\", \"Third Party Advisory\"], \"source\": \"secalert@redhat.com\"}, {\"url\": \"https://lists.debian.org/debian-lts-announce/2023/05/msg00024.html\", \"source\": \"secalert@redhat.com\"}, {\"url\": \"https://lists.debian.org/debian-lts-announce/2023/06/msg00039.html\", \"source\": \"secalert@redhat.com\"}, {\"url\": \"https://python-security.readthedocs.io/vuln/ftplib-pasv.html\", \"tags\": [\"Patch\", \"Third Party Advisory\"], \"source\": \"secalert@redhat.com\"}, {\"url\": \"https://security-tracker.debian.org/tracker/CVE-2021-4189\", \"tags\": [\"Third Party Advisory\"], \"source\": \"secalert@redhat.com\"}, {\"url\": \"https://security.netapp.com/advisory/ntap-20221104-0004/\", \"tags\": [\"Third Party Advisory\"], \"source\": \"secalert@redhat.com\"}, {\"url\": \"https://access.redhat.com/security/cve/CVE-2021-4189\", \"tags\": [\"Third Party Advisory\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://bugs.python.org/issue43285\", \"tags\": [\"Patch\", \"Vendor Advisory\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://bugzilla.redhat.com/show_bug.cgi?id=2036020\", \"tags\": [\"Issue Tracking\", \"Patch\", \"Third Party Advisory\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://github.com/python/cpython/commit/0ab152c6b5d95caa2dc1a30fa96e10258b5f188e\", \"tags\": [\"Patch\", \"Third Party Advisory\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://lists.debian.org/debian-lts-announce/2023/05/msg00024.html\", \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://lists.debian.org/debian-lts-announce/2023/06/msg00039.html\", \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://python-security.readthedocs.io/vuln/ftplib-pasv.html\", \"tags\": [\"Patch\", \"Third Party Advisory\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://security-tracker.debian.org/tracker/CVE-2021-4189\", \"tags\": [\"Third Party Advisory\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://security.netapp.com/advisory/ntap-20221104-0004/\", \"tags\": [\"Third Party Advisory\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}], \"vulnStatus\": \"Modified\", \"weaknesses\": [{\"type\": \"Primary\", \"source\": \"nvd@nist.gov\", \"description\": [{\"lang\": \"en\", \"value\": \"CWE-252\"}]}], \"descriptions\": [{\"lang\": \"en\", \"value\": \"A flaw was found in Python, specifically in the FTP (File Transfer Protocol) client library in PASV (passive) mode. The issue is how the FTP client trusts the host from the PASV response by default. This flaw allows an attacker to set up a malicious FTP server that can trick FTP clients into connecting back to a given IP address and port. This vulnerability could lead to FTP client scanning ports, which otherwise would not have been possible.\"}, {\"lang\": \"es\", \"value\": \"Se ha encontrado un fallo en Python, concretamente en la biblioteca del cliente FTP (File Transfer Protocol) en modo PASV (pasivo). El problema radica en c\\u00f3mo el cliente FTP conf\\u00eda en el host a partir de la respuesta PASV por defecto. Este fallo permite a un atacante configurar un servidor FTP malicioso que puede enga\\u00f1ar a los clientes FTP para que sean conectados a una direcci\\u00f3n IP y un puerto determinados. Esta vulnerabilidad podr\\u00eda conllevar a que los clientes FTP escanearan los puertos, lo que de otro modo no habr\\u00eda sido posible.\"}], \"lastModified\": \"2024-11-21T06:37:06.437\", \"configurations\": [{\"nodes\": [{\"negate\": false, \"cpeMatch\": [{\"criteria\": \"cpe:2.3:a:python:python:*:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"98AE93B0-882A-42C5-B3A4-8B4D810AB111\", \"versionEndExcluding\": \"3.6.14\", \"versionStartIncluding\": \"3.6.0\"}, {\"criteria\": \"cpe:2.3:a:python:python:*:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"63D83236-D590-43D4-82C0-B0C656E02A29\", \"versionEndExcluding\": \"3.7.11\", \"versionStartIncluding\": \"3.7.0\"}, {\"criteria\": \"cpe:2.3:a:python:python:*:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"A39F58D2-FB1D-4865-AF30-1A529F467D74\", \"versionEndExcluding\": \"3.8.9\", \"versionStartIncluding\": \"3.8.0\"}, {\"criteria\": \"cpe:2.3:a:python:python:*:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"B19E0ABC-7E51-4870-BE02-F9D41409BE58\", \"versionEndExcluding\": \"3.9.3\", \"versionStartIncluding\": \"3.9.0\"}, {\"criteria\": \"cpe:2.3:a:python:python:3.10.0:-:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"36027ED3-D643-4ACE-A43C-725C8E0BD99F\"}], \"operator\": \"OR\"}]}, {\"nodes\": [{\"negate\": false, \"cpeMatch\": [{\"criteria\": \"cpe:2.3:o:debian:debian_linux:10.0:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"07B237A9-69A3-4A9C-9DA0-4E06BD37AE73\"}, {\"criteria\": \"cpe:2.3:o:debian:debian_linux:11.0:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"FA6FEEC2-9F11-4643-8827-749718254FED\"}], \"operator\": \"OR\"}]}, {\"nodes\": [{\"negate\": false, \"cpeMatch\": [{\"criteria\": \"cpe:2.3:a:redhat:software_collections:-:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"749804DA-4B27-492A-9ABA-6BB562A6B3AC\"}, {\"criteria\": \"cpe:2.3:o:redhat:enterprise_linux:8.0:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"F4CFF558-3C47-480D-A2F0-BABF26042943\"}], \"operator\": \"OR\"}]}, {\"nodes\": [{\"negate\": false, \"cpeMatch\": [{\"criteria\": \"cpe:2.3:a:netapp:ontap_select_deploy_administration_utility:-:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"E7CF3019-975D-40BB-A8A4-894E62BD3797\"}], \"operator\": \"OR\"}]}], \"sourceIdentifier\": \"secalert@redhat.com\"}}\n",
    "LastUpdate": 0,
    "VendorL": [
      "python",
      "debian",
      "redhat",
      "netapp"
    ],
    "ProductL": [
      "python",
      "debian_linux",
      "enterprise_linux",
      "software_collections",
      "ontap_select_deploy_administration_utility"
    ],
    "Software_Repo_Mappings": []
  },
  "Software_Repo_Mapping_Conditions": [
    {
      "Software_Repo_Mapping_ConditionId": 0,
      "Software_Repo_MappingId": null,
      "Criteria": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
      "VersionEndExcluding": "3.6.14",
      "VersionEndIncluding": null,
      "VersionStartExcluding": null,
      "VersionStartIncluding": "3.6.0",
      "Vulnerable": true,
      "Software_Repo_Mapping": null
    },
    {
      "Software_Repo_Mapping_ConditionId": 0,
      "Software_Repo_MappingId": null,
      "Criteria": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
      "VersionEndExcluding": "3.7.11",
      "VersionEndIncluding": null,
      "VersionStartExcluding": null,
      "VersionStartIncluding": "3.7.0",
      "Vulnerable": true,
      "Software_Repo_Mapping": null
    },
    {
      "Software_Repo_Mapping_ConditionId": 0,
      "Software_Repo_MappingId": null,
      "Criteria": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
      "VersionEndExcluding": "3.8.9",
      "VersionEndIncluding": null,
      "VersionStartExcluding": null,
      "VersionStartIncluding": "3.8.0",
      "Vulnerable": true,
      "Software_Repo_Mapping": null
    },
    {
      "Software_Repo_Mapping_ConditionId": 0,
      "Software_Repo_MappingId": null,
      "Criteria": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
      "VersionEndExcluding": "3.9.3",
      "VersionEndIncluding": null,
      "VersionStartExcluding": null,
      "VersionStartIncluding": "3.9.0",
      "Vulnerable": true,
      "Software_Repo_Mapping": null
    },
    {
      "Software_Repo_Mapping_ConditionId": 0,
      "Software_Repo_MappingId": null,
      "Criteria": "cpe:2.3:a:python:python:3.10.0:-:*:*:*:*:*:*",
      "VersionEndExcluding": null,
      "VersionEndIncluding": null,
      "VersionStartExcluding": null,
      "VersionStartIncluding": null,
      "Vulnerable": true,
      "Software_Repo_Mapping": null
    }
  ]
}