{
  "Software_Repo_MappingId": null,
  "Software_RepoId": "f6b863cd-8f1c-4583-8bc5-ee59e86e5cf1",
  "Software_Name": "Python 3.12.5 (64-bit)",
  "CVEID": "CVE-2019-18348",
  "Summary": "An issue was discovered in urllib2 in Python 2.x through 2.7.17 and urllib in Python 3.x through 3.8.0. CRLF injection is possible if the attacker controls a url parameter, as demonstrated by the first argument to urllib.request.urlopen with \\r\\n (specifically in the host component of a URL) followed by an HTTP header. This is similar to the CVE-2019-9740 query string issue and the CVE-2019-9947 path string issue. (This is not exploitable when glibc has CVE-2016-10739 fixed.). This is fixed in: v2.7.18, v2.7.18rc1; v3.5.10, v3.5.10rc1; v3.6.11, v3.6.11rc1, v3.6.12; v3.7.8, v3.7.8rc1, v3.7.9; v3.8.3, v3.8.3rc1, v3.8.4, v3.8.4rc1, v3.8.5, v3.8.6, v3.8.6rc1.",
  "LastUpdate": 0,
  "CVEE": {
    "CVEEId": "CVE-2019-18348",
    "CVSS_V2_baseScore": 4.3,
    "CVSS_V2_Data": "{\"version\":\"2.0\",\"baseScore\":4.3,\"accessVector\":\"NETWORK\",\"vectorString\":\"AV:N/AC:M/Au:N/C:N/I:P/A:N\",\"authentication\":\"NONE\",\"integrityImpact\":\"PARTIAL\",\"accessComplexity\":\"MEDIUM\",\"availabilityImpact\":\"NONE\",\"confidentialityImpact\":\"NONE\",\"scope\":null,\"attackVector\":null,\"baseSeverity\":null,\"userInteraction\":null,\"attackComplexity\":null,\"privilegesRequired\":null}",
    "CVSS_V3_baseScore": 6.1,
    "CVSS_V3_Data": "{\"version\":\"3.1\",\"baseScore\":6.1,\"accessVector\":null,\"vectorString\":\"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N\",\"authentication\":null,\"integrityImpact\":\"LOW\",\"accessComplexity\":null,\"availabilityImpact\":\"NONE\",\"confidentialityImpact\":\"LOW\",\"scope\":\"CHANGED\",\"attackVector\":\"NETWORK\",\"baseSeverity\":\"MEDIUM\",\"userInteraction\":\"REQUIRED\",\"attackComplexity\":\"LOW\",\"privilegesRequired\":\"NONE\"}",
    "PublishedDate": "2019-10-23T17:15:12.973",
    "ModifyDate": "2024-11-21T04:33:06.653",
    "VulnStatus": "Modified",
    "JsonData": "{\"id\": \"CVE-2019-18348\", \"summary\": \"An issue was discovered in urllib2 in Python 2.x through 2.7.17 and urllib in Python 3.x through 3.8.0. CRLF injection is possible if the attacker controls a url parameter, as demonstrated by the first argument to urllib.request.urlopen with \\\\r\\\\n (specifically in the host component of a URL) followed by an HTTP header. This is similar to the CVE-2019-9740 query string issue and the CVE-2019-9947 path string issue. (This is not exploitable when glibc has CVE-2016-10739 fixed.). This is fixed in: v2.7.18, v2.7.18rc1; v3.5.10, v3.5.10rc1; v3.6.11, v3.6.11rc1, v3.6.12; v3.7.8, v3.7.8rc1, v3.7.9; v3.8.3, v3.8.3rc1, v3.8.4, v3.8.4rc1, v3.8.5, v3.8.6, v3.8.6rc1.\", \"created_at\": \"2019-10-23T17:15:12Z\", \"updated_at\": \"2024-11-21T04:33:06Z\", \"cvss\": {\"v2\": 4.3, \"v3\": 6.1}, \"vendors\": {\"python\": [\"python\"]}, \"cwes\": [\"CWE-74\"], \"raw_nvd_data\": {\"id\": \"CVE-2019-18348\", \"metrics\": {\"cvssMetricV2\": [{\"type\": \"Primary\", \"source\": \"nvd@nist.gov\", \"cvssData\": {\"version\": \"2.0\", \"baseScore\": 4.3, \"accessVector\": \"NETWORK\", \"vectorString\": \"AV:N/AC:M/Au:N/C:N/I:P/A:N\", \"authentication\": \"NONE\", \"integrityImpact\": \"PARTIAL\", \"accessComplexity\": \"MEDIUM\", \"availabilityImpact\": \"NONE\", \"confidentialityImpact\": \"NONE\"}, \"acInsufInfo\": false, \"impactScore\": 2.9, \"baseSeverity\": \"MEDIUM\", \"obtainAllPrivilege\": false, \"exploitabilityScore\": 8.6, \"obtainUserPrivilege\": false, \"obtainOtherPrivilege\": false, \"userInteractionRequired\": true}], \"cvssMetricV31\": [{\"type\": \"Primary\", \"source\": \"nvd@nist.gov\", \"cvssData\": {\"scope\": \"CHANGED\", \"version\": \"3.1\", \"baseScore\": 6.1, \"attackVector\": \"NETWORK\", \"baseSeverity\": \"MEDIUM\", \"vectorString\": \"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N\", \"integrityImpact\": \"LOW\", \"userInteraction\": \"REQUIRED\", \"attackComplexity\": \"LOW\", \"availabilityImpact\": \"NONE\", \"privilegesRequired\": \"NONE\", \"confidentialityImpact\": \"LOW\"}, \"impactScore\": 2.7, \"exploitabilityScore\": 2.8}]}, \"published\": \"2019-10-23T17:15:12.973\", \"references\": [{\"url\": \"http://lists.opensuse.org/opensuse-security-announce/2020-05/msg00041.html\", \"tags\": [\"Mailing List\", \"Technical Description\"], \"source\": \"cve@mitre.org\"}, {\"url\": \"https://bugs.python.org/issue30458#msg347282\", \"tags\": [\"Issue Tracking\", \"Vendor Advisory\"], \"source\": \"cve@mitre.org\"}, {\"url\": \"https://bugzilla.redhat.com/show_bug.cgi?id=1727276\", \"tags\": [\"Issue Tracking\", \"Third Party Advisory\"], \"source\": \"cve@mitre.org\"}, {\"url\": \"https://lists.debian.org/debian-lts-announce/2020/07/msg00011.html\", \"tags\": [\"Mailing List\", \"Technical Description\"], \"source\": \"cve@mitre.org\"}, {\"url\": \"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/4X3HW5JRZ7GCPSR7UHJOLD7AWLTQCDVR/\", \"source\": \"cve@mitre.org\"}, {\"url\": \"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/A5NSAX4SC3V64PGZUPH7PRDLSON34Q5A/\", \"source\": \"cve@mitre.org\"}, {\"url\": \"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/JCPGLTTOBB3QEARDX4JOYURP6ELNNA2V/\", \"source\": \"cve@mitre.org\"}, {\"url\": \"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/M34WOYCDKTDE5KLUACE2YIEH7D37KHRX/\", \"source\": \"cve@mitre.org\"}, {\"url\": \"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/UESGYI5XDAHJBATEZN3MHNDUBDH47AS6/\", \"source\": \"cve@mitre.org\"}, {\"url\": \"https://security.netapp.com/advisory/ntap-20191107-0004/\", \"tags\": [\"Technical Description\"], \"source\": \"cve@mitre.org\"}, {\"url\": \"https://usn.ubuntu.com/4333-1/\", \"tags\": [\"Technical Description\"], \"source\": \"cve@mitre.org\"}, {\"url\": \"https://usn.ubuntu.com/4333-2/\", \"tags\": [\"Technical Description\"], \"source\": \"cve@mitre.org\"}, {\"url\": \"https://www.oracle.com/security-alerts/cpuoct2020.html\", \"tags\": [\"Technical Description\"], \"source\": \"cve@mitre.org\"}, {\"url\": \"http://lists.opensuse.org/opensuse-security-announce/2020-05/msg00041.html\", \"tags\": [\"Mailing List\", \"Technical Description\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://bugs.python.org/issue30458#msg347282\", \"tags\": [\"Issue Tracking\", \"Vendor Advisory\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://bugzilla.redhat.com/show_bug.cgi?id=1727276\", \"tags\": [\"Issue Tracking\", \"Third Party Advisory\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://lists.debian.org/debian-lts-announce/2020/07/msg00011.html\", \"tags\": [\"Mailing List\", \"Technical Description\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/4X3HW5JRZ7GCPSR7UHJOLD7AWLTQCDVR/\", \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/A5NSAX4SC3V64PGZUPH7PRDLSON34Q5A/\", \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/JCPGLTTOBB3QEARDX4JOYURP6ELNNA2V/\", \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/M34WOYCDKTDE5KLUACE2YIEH7D37KHRX/\", \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/UESGYI5XDAHJBATEZN3MHNDUBDH47AS6/\", \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://security.netapp.com/advisory/ntap-20191107-0004/\", \"tags\": [\"Technical Description\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://usn.ubuntu.com/4333-1/\", \"tags\": [\"Technical Description\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://usn.ubuntu.com/4333-2/\", \"tags\": [\"Technical Description\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://www.oracle.com/security-alerts/cpuoct2020.html\", \"tags\": [\"Technical Description\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}], \"vulnStatus\": \"Modified\", \"weaknesses\": [{\"type\": \"Primary\", \"source\": \"nvd@nist.gov\", \"description\": [{\"lang\": \"en\", \"value\": \"CWE-74\"}]}], \"descriptions\": [{\"lang\": \"en\", \"value\": \"An issue was discovered in urllib2 in Python 2.x through 2.7.17 and urllib in Python 3.x through 3.8.0. CRLF injection is possible if the attacker controls a url parameter, as demonstrated by the first argument to urllib.request.urlopen with \\\\r\\\\n (specifically in the host component of a URL) followed by an HTTP header. This is similar to the CVE-2019-9740 query string issue and the CVE-2019-9947 path string issue. (This is not exploitable when glibc has CVE-2016-10739 fixed.). This is fixed in: v2.7.18, v2.7.18rc1; v3.5.10, v3.5.10rc1; v3.6.11, v3.6.11rc1, v3.6.12; v3.7.8, v3.7.8rc1, v3.7.9; v3.8.3, v3.8.3rc1, v3.8.4, v3.8.4rc1, v3.8.5, v3.8.6, v3.8.6rc1.\"}, {\"lang\": \"es\", \"value\": \"Se detect\\u00f3 un problema en urllib2 en Python versiones 2.x hasta 2.7.17 y urllib en Python versiones 3.x hasta 3.8.0. La inyecci\\u00f3n de CRLF es posible si el atacante controla un par\\u00e1metro url, como es demostrado por el primer argumento para urllib.request.urlopen con \\\\ r\\\\n (espec\\u00edficamente en el componente host de una URL) seguido de un encabezado HTTP. Esto es similar al problema de la cadena de consulta de CVE-2019-9740 y al problema de la cadena de ruta de CVE-2019-9947. (Esto no es explotable cuando glibc tiene corregido el CVE-2016-10739). Esto est\\u00e1 corregido en las versiones: v2.7.18, v2.7.18rc1; v3.5.10, v3.5.10rc1; v3.6.11, v3.6.11rc1, v3.6.12; v3.7.8, v3.7.8rc1, v3.7.9; v3.8.3, v3.8.3rc1, v3.8.4, v3.8.4rc1, v3.8.5, v3.8.6, v3.8.6rc1\"}], \"lastModified\": \"2024-11-21T04:33:06.653\", \"configurations\": [{\"nodes\": [{\"negate\": false, \"cpeMatch\": [{\"criteria\": \"cpe:2.3:a:python:python:*:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"1CBD119B-076B-46D3-9B94-FABC14564E96\", \"versionEndIncluding\": \"2.7.17\", \"versionStartIncluding\": \"2.0\"}, {\"criteria\": \"cpe:2.3:a:python:python:*:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"8041A276-2D5F-493F-BD14-17C96BDFFA8D\", \"versionEndExcluding\": \"3.5.10\", \"versionStartIncluding\": \"3.0\"}, {\"criteria\": \"cpe:2.3:a:python:python:*:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"EC082AF5-7781-4AA9-B899-26B0D275FA3D\", \"versionEndExcluding\": \"3.6.11\", \"versionStartIncluding\": \"3.6.0\"}, {\"criteria\": \"cpe:2.3:a:python:python:*:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"BEB8C981-BD15-4E7B-B11A-0FC9A00BD654\", \"versionEndExcluding\": \"3.7.8\", \"versionStartIncluding\": \"3.7.0\"}, {\"criteria\": \"cpe:2.3:a:python:python:*:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"2FD7A4CD-2414-490D-BCA7-BDFAD3B6D164\", \"versionEndExcluding\": \"3.8.3\", \"versionStartIncluding\": \"3.8.0\"}], \"operator\": \"OR\"}]}], \"sourceIdentifier\": \"cve@mitre.org\"}}\n",
    "LastUpdate": 0,
    "VendorL": [
      "python"
    ],
    "ProductL": [
      "python"
    ],
    "Software_Repo_Mappings": []
  },
  "Software_Repo_Mapping_Conditions": [
    {
      "Software_Repo_Mapping_ConditionId": 0,
      "Software_Repo_MappingId": null,
      "Criteria": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
      "VersionEndExcluding": null,
      "VersionEndIncluding": "2.7.17",
      "VersionStartExcluding": null,
      "VersionStartIncluding": "2.0",
      "Vulnerable": true,
      "Software_Repo_Mapping": null
    },
    {
      "Software_Repo_Mapping_ConditionId": 0,
      "Software_Repo_MappingId": null,
      "Criteria": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
      "VersionEndExcluding": "3.5.10",
      "VersionEndIncluding": null,
      "VersionStartExcluding": null,
      "VersionStartIncluding": "3.0",
      "Vulnerable": true,
      "Software_Repo_Mapping": null
    },
    {
      "Software_Repo_Mapping_ConditionId": 0,
      "Software_Repo_MappingId": null,
      "Criteria": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
      "VersionEndExcluding": "3.6.11",
      "VersionEndIncluding": null,
      "VersionStartExcluding": null,
      "VersionStartIncluding": "3.6.0",
      "Vulnerable": true,
      "Software_Repo_Mapping": null
    },
    {
      "Software_Repo_Mapping_ConditionId": 0,
      "Software_Repo_MappingId": null,
      "Criteria": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
      "VersionEndExcluding": "3.7.8",
      "VersionEndIncluding": null,
      "VersionStartExcluding": null,
      "VersionStartIncluding": "3.7.0",
      "Vulnerable": true,
      "Software_Repo_Mapping": null
    },
    {
      "Software_Repo_Mapping_ConditionId": 0,
      "Software_Repo_MappingId": null,
      "Criteria": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
      "VersionEndExcluding": "3.8.3",
      "VersionEndIncluding": null,
      "VersionStartExcluding": null,
      "VersionStartIncluding": "3.8.0",
      "Vulnerable": true,
      "Software_Repo_Mapping": null
    }
  ]
}